------------------------------------------------------------------------
-- HEALTH_DOMAIN — PHASE 9: AUDIT
-- Login, grants, user tracking views
------------------------------------------------------------------------

USE ROLE ACCOUNTADMIN;

-- 1. Login audit – all login attempts (last 30 days)
CREATE OR REPLACE VIEW HEALTH_GOVERNANCE_DB.AUDIT.V_LOGIN_AUDIT AS
SELECT
    EVENT_TIMESTAMP,
    USER_NAME,
    CLIENT_IP,
    REPORTED_CLIENT_TYPE,
    REPORTED_CLIENT_VERSION,
    FIRST_AUTHENTICATION_FACTOR,
    IS_SUCCESS,
    ERROR_CODE,
    ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE EVENT_TIMESTAMP >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
ORDER BY EVENT_TIMESTAMP DESC;

-- 2. Failed logins detail
CREATE OR REPLACE VIEW HEALTH_GOVERNANCE_DB.AUDIT.V_FAILED_LOGINS AS
SELECT
    EVENT_TIMESTAMP,
    USER_NAME,
    CLIENT_IP,
    REPORTED_CLIENT_TYPE,
    ERROR_CODE,
    ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE IS_SUCCESS = 'NO'
  AND EVENT_TIMESTAMP >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
ORDER BY EVENT_TIMESTAMP DESC;

-- 3. Grant changes audit (last 90 days)
CREATE OR REPLACE VIEW HEALTH_GOVERNANCE_DB.AUDIT.V_GRANT_CHANGES AS
SELECT
    CREATED_ON,
    MODIFIED_ON,
    PRIVILEGE,
    GRANTED_ON,
    NAME          AS OBJECT_NAME,
    TABLE_CATALOG AS DATABASE_NAME,
    TABLE_SCHEMA  AS SCHEMA_NAME,
    GRANTED_TO,
    GRANTEE_NAME,
    GRANT_OPTION,
    GRANTED_BY
FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES
WHERE CREATED_ON >= DATEADD('DAY', -90, CURRENT_TIMESTAMP())
ORDER BY CREATED_ON DESC;

-- 4. Role grants to users
CREATE OR REPLACE VIEW HEALTH_GOVERNANCE_DB.AUDIT.V_ROLE_GRANTS_TO_USERS AS
SELECT
    CREATED_ON,
    ROLE,
    GRANTED_TO,
    GRANTEE_NAME,
    GRANTED_BY
FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS
WHERE CREATED_ON >= DATEADD('DAY', -90, CURRENT_TIMESTAMP())
ORDER BY CREATED_ON DESC;

-- 5. User inventory and last login
CREATE OR REPLACE VIEW HEALTH_GOVERNANCE_DB.AUDIT.V_USER_INVENTORY AS
SELECT
    NAME            AS USER_NAME,
    LOGIN_NAME,
    DISPLAY_NAME,
    EMAIL,
    DEFAULT_ROLE,
    DEFAULT_WAREHOUSE,
    CREATED_ON,
    LAST_SUCCESS_LOGIN,
    DISABLED,
    LOCKED,
    HAS_MFA,
    DATEDIFF('DAY', LAST_SUCCESS_LOGIN, CURRENT_TIMESTAMP()) AS DAYS_SINCE_LAST_LOGIN
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS
ORDER BY LAST_SUCCESS_LOGIN DESC NULLS LAST;

-- 6. Dormant users (no login in 30+ days)
CREATE OR REPLACE VIEW HEALTH_GOVERNANCE_DB.AUDIT.V_DORMANT_USERS AS
SELECT
    NAME            AS USER_NAME,
    EMAIL,
    DEFAULT_ROLE,
    LAST_SUCCESS_LOGIN,
    DATEDIFF('DAY', LAST_SUCCESS_LOGIN, CURRENT_TIMESTAMP()) AS DAYS_INACTIVE
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS
WHERE DISABLED = 'false'
  AND (LAST_SUCCESS_LOGIN IS NULL
       OR LAST_SUCCESS_LOGIN < DATEADD('DAY', -30, CURRENT_TIMESTAMP()))
ORDER BY DAYS_INACTIVE DESC NULLS FIRST;

-- 7. PHI access tracking – queries touching sensitive tables
CREATE OR REPLACE VIEW HEALTH_GOVERNANCE_DB.AUDIT.V_PHI_ACCESS_LOG AS
SELECT
    QH.QUERY_ID,
    QH.USER_NAME,
    QH.ROLE_NAME,
    QH.WAREHOUSE_NAME,
    QH.START_TIME,
    AH.DIRECT_OBJECTS_ACCESSED,
    QH.QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY QH
JOIN SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY AH
  ON QH.QUERY_ID = AH.QUERY_ID
WHERE QH.START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
  AND ARRAY_TO_STRING(AH.DIRECT_OBJECTS_ACCESSED, ',') ILIKE '%PATIENT%'
ORDER BY QH.START_TIME DESC;

-- 8. ACCOUNTADMIN usage tracking
CREATE OR REPLACE VIEW HEALTH_GOVERNANCE_DB.AUDIT.V_ACCOUNTADMIN_USAGE AS
SELECT
    QUERY_ID,
    USER_NAME,
    START_TIME,
    END_TIME,
    QUERY_TEXT,
    EXECUTION_STATUS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE ROLE_NAME = 'ACCOUNTADMIN'
  AND START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC;

-- 9. DDL change log (CREATE/ALTER/DROP)
CREATE OR REPLACE VIEW HEALTH_GOVERNANCE_DB.AUDIT.V_DDL_CHANGE_LOG AS
SELECT
    QUERY_ID,
    USER_NAME,
    ROLE_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    START_TIME,
    QUERY_TYPE,
    QUERY_TEXT,
    EXECUTION_STATUS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TYPE IN ('CREATE_TABLE', 'ALTER_TABLE', 'DROP_TABLE',
                     'CREATE_VIEW', 'ALTER_VIEW', 'DROP_VIEW',
                     'CREATE_SCHEMA', 'DROP_SCHEMA',
                     'CREATE_DATABASE', 'DROP_DATABASE',
                     'GRANT', 'REVOKE')
  AND START_TIME >= DATEADD('DAY', -90, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC;

-- 10. Session activity summary
CREATE OR REPLACE VIEW HEALTH_GOVERNANCE_DB.AUDIT.V_SESSION_ACTIVITY AS
SELECT
    USER_NAME,
    DATE_TRUNC('DAY', CREATED_ON)::DATE AS SESSION_DATE,
    COUNT(*)                              AS SESSION_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.SESSIONS
WHERE CREATED_ON >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
GROUP BY 1, 2
ORDER BY 2 DESC, 3 DESC;

GRANT SELECT ON ALL VIEWS IN SCHEMA HEALTH_GOVERNANCE_DB.AUDIT TO ROLE HEALTH_GOVERNANCE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HEALTH_GOVERNANCE_DB.AUDIT TO ROLE HEALTH_GOVERNANCE;
