------------------------------------------------------------------------
-- HEALTH_DOMAIN — PHASE 13: AI-READY LAYER
-- Feature store, semantic models, embeddings
-- Grounded in PyHealth & Cardiac Rehabilitation skill context
------------------------------------------------------------------------

USE ROLE HEALTH_ADMIN;
USE WAREHOUSE HEALTH_AI_WH;

------------------------------------------------------------------------
-- 13A. FEATURE STORE – Pre-computed ML features
------------------------------------------------------------------------

-- Patient-level feature table for mortality / readmission prediction
CREATE OR REPLACE TABLE HEALTH_AI_READY_DB.FEATURE_STORE.PATIENT_CLINICAL_FEATURES AS
SELECT
    P.PATIENT_ID,
    P.AGE,
    P.GENDER,
    P.ETHNICITY,

    -- Diagnosis features
    COALESCE(DX.TOTAL_DIAGNOSES, 0)         AS TOTAL_DIAGNOSES,
    COALESCE(DX.UNIQUE_ICD_CODES, 0)        AS UNIQUE_ICD_CODES,
    COALESCE(DX.HAS_MI, FALSE)              AS HAS_MI,
    COALESCE(DX.HAS_HF, FALSE)             AS HAS_HEART_FAILURE,
    COALESCE(DX.HAS_AFIB, FALSE)           AS HAS_ATRIAL_FIB,

    -- Medication features
    COALESCE(MED.TOTAL_MEDICATIONS, 0)       AS TOTAL_MEDICATIONS,
    COALESCE(MED.ON_BETA_BLOCKER, FALSE)    AS ON_BETA_BLOCKER,
    COALESCE(MED.ON_ACE_INHIBITOR, FALSE)   AS ON_ACE_INHIBITOR,
    COALESCE(MED.ON_ANTICOAGULANT, FALSE)   AS ON_ANTICOAGULANT,
    COALESCE(MED.ON_STATIN, FALSE)          AS ON_STATIN,
    COALESCE(MED.DRUG_CLASS_COUNT, 0)       AS DISTINCT_DRUG_CLASSES,

    -- Encounter features
    COALESCE(ENC.TOTAL_ENCOUNTERS, 0)        AS TOTAL_ENCOUNTERS,
    COALESCE(ENC.INPATIENT_COUNT, 0)        AS INPATIENT_VISITS,
    COALESCE(ENC.AVG_LOS_DAYS, 0)          AS AVG_LENGTH_OF_STAY,
    COALESCE(ENC.MAX_LOS_DAYS, 0)          AS MAX_LENGTH_OF_STAY,

    -- Lab features (latest)
    LAB.LATEST_HBA1C,
    LAB.LATEST_LDL,
    LAB.LATEST_HDL,
    LAB.LATEST_TOTAL_CHOLESTEROL,
    LAB.ABNORMAL_LAB_RATIO,

    CURRENT_TIMESTAMP()                      AS FEATURE_COMPUTED_AT

FROM HEALTH_TRANSFORM_DB.PATIENTS.DIM_PATIENT P

LEFT JOIN (
    SELECT
        PATIENT_ID,
        COUNT(*)                                      AS TOTAL_DIAGNOSES,
        COUNT(DISTINCT ICD_CODE)                      AS UNIQUE_ICD_CODES,
        MAX(CASE WHEN CARDIAC_CATEGORY = 'ACUTE_MI' THEN TRUE ELSE FALSE END) AS HAS_MI,
        MAX(CASE WHEN CARDIAC_CATEGORY = 'HEART_FAILURE' THEN TRUE ELSE FALSE END) AS HAS_HF,
        MAX(CASE WHEN CARDIAC_CATEGORY = 'ATRIAL_FIBRILLATION' THEN TRUE ELSE FALSE END) AS HAS_AFIB
    FROM HEALTH_TRANSFORM_DB.DIAGNOSES.FACT_DIAGNOSIS
    GROUP BY PATIENT_ID
) DX ON P.PATIENT_ID = DX.PATIENT_ID

LEFT JOIN (
    SELECT
        PATIENT_ID,
        COUNT(*)                                                                  AS TOTAL_MEDICATIONS,
        MAX(CASE WHEN DRUG_CLASS = 'BETA_BLOCKER'  THEN TRUE ELSE FALSE END)    AS ON_BETA_BLOCKER,
        MAX(CASE WHEN DRUG_CLASS = 'ACE_INHIBITOR'  THEN TRUE ELSE FALSE END)   AS ON_ACE_INHIBITOR,
        MAX(CASE WHEN DRUG_CLASS = 'ANTICOAGULANT'  THEN TRUE ELSE FALSE END)   AS ON_ANTICOAGULANT,
        MAX(CASE WHEN DRUG_CLASS = 'STATIN'          THEN TRUE ELSE FALSE END)  AS ON_STATIN,
        COUNT(DISTINCT DRUG_CLASS)                                                AS DRUG_CLASS_COUNT
    FROM HEALTH_TRANSFORM_DB.MEDICATIONS.FACT_MEDICATION
    GROUP BY PATIENT_ID
) MED ON P.PATIENT_ID = MED.PATIENT_ID

LEFT JOIN (
    SELECT
        PATIENT_ID,
        COUNT(*)                                                    AS TOTAL_ENCOUNTERS,
        SUM(CASE WHEN ENCOUNTER_TYPE = 'INPATIENT' THEN 1 ELSE 0 END) AS INPATIENT_COUNT,
        AVG(LENGTH_OF_STAY_DAYS)                                    AS AVG_LOS_DAYS,
        MAX(LENGTH_OF_STAY_DAYS)                                    AS MAX_LOS_DAYS
    FROM HEALTH_TRANSFORM_DB.ENCOUNTERS.FACT_ENCOUNTER
    GROUP BY PATIENT_ID
) ENC ON P.PATIENT_ID = ENC.PATIENT_ID

LEFT JOIN (
    SELECT
        PATIENT_ID,
        MAX(CASE WHEN TEST_NAME ILIKE '%hba1c%'       THEN RESULT_NUMERIC END) AS LATEST_HBA1C,
        MAX(CASE WHEN TEST_NAME ILIKE '%ldl%'          THEN RESULT_NUMERIC END) AS LATEST_LDL,
        MAX(CASE WHEN TEST_NAME ILIKE '%hdl%'          THEN RESULT_NUMERIC END) AS LATEST_HDL,
        MAX(CASE WHEN TEST_NAME ILIKE '%cholesterol%'  THEN RESULT_NUMERIC END) AS LATEST_TOTAL_CHOLESTEROL,
        ROUND(SUM(CASE WHEN COMPUTED_FLAG IN ('HIGH','LOW') THEN 1 ELSE 0 END)::FLOAT
              / NULLIF(COUNT(*), 0), 3) AS ABNORMAL_LAB_RATIO
    FROM HEALTH_TRANSFORM_DB.LAB_VITALS.FACT_LAB_RESULT
    GROUP BY PATIENT_ID
) LAB ON P.PATIENT_ID = LAB.PATIENT_ID;

ALTER TABLE HEALTH_AI_READY_DB.FEATURE_STORE.PATIENT_CLINICAL_FEATURES
  SET TAG HEALTH_GOVERNANCE_DB.TAGS.DATA_DOMAIN = 'RESEARCH';

-- Cardiac rehab feature table (for PyHealth-style models: RETAIN, Transformer)
CREATE OR REPLACE TABLE HEALTH_AI_READY_DB.FEATURE_STORE.CARDIAC_REHAB_FEATURES AS
SELECT
    S.PATIENT_ID,
    S.REFERRAL_ID,
    S.SESSION_ID,
    S.SESSION_NUMBER,
    R.COMPUTED_RISK                  AS RISK_CATEGORY,
    R.LVEF_PERCENT,
    R.GXT_PEAK_METS,

    -- Session hemodynamics (normalised)
    S.RESTING_HR,
    S.PEAK_HR,
    S.RECOVERY_HR,
    S.HR_RECOVERY_DELTA,
    S.ACHIEVED_HRR_PERCENT,
    S.RESTING_BP_SYSTOLIC,
    S.PEAK_BP_SYSTOLIC,
    S.RPE_PEAK,
    S.SPO2_MIN,
    S.DURATION_MINUTES,
    S.ECG_MONITOR_MINUTES,
    S.SAFETY_FLAG,
    S.EXERCISE_TERMINATED_EARLY,

    -- Rolling window features (last 3 sessions)
    AVG(S.PEAK_HR) OVER (PARTITION BY S.PATIENT_ID ORDER BY S.SESSION_NUMBER
                          ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS ROLLING_3_AVG_PEAK_HR,
    AVG(S.RPE_PEAK) OVER (PARTITION BY S.PATIENT_ID ORDER BY S.SESSION_NUMBER
                           ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS ROLLING_3_AVG_RPE,
    AVG(S.DURATION_MINUTES) OVER (PARTITION BY S.PATIENT_ID ORDER BY S.SESSION_NUMBER
                                   ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS ROLLING_3_AVG_DURATION,

    -- Progression indicators
    S.PEAK_HR - LAG(S.PEAK_HR) OVER (PARTITION BY S.PATIENT_ID ORDER BY S.SESSION_NUMBER) AS PEAK_HR_DELTA,
    S.RPE_PEAK - LAG(S.RPE_PEAK) OVER (PARTITION BY S.PATIENT_ID ORDER BY S.SESSION_NUMBER) AS RPE_DELTA,
    S.DURATION_MINUTES - LAG(S.DURATION_MINUTES) OVER (PARTITION BY S.PATIENT_ID ORDER BY S.SESSION_NUMBER) AS DURATION_DELTA,

    CURRENT_TIMESTAMP() AS FEATURE_COMPUTED_AT

FROM HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_SESSION S
JOIN HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_REFERRAL R
  ON S.REFERRAL_ID = R.REFERRAL_ID;

------------------------------------------------------------------------
-- 13B. TRAINING DATASETS – Versioned snapshots for model training
------------------------------------------------------------------------

-- Mortality prediction training set (PyHealth-compatible structure)
CREATE OR REPLACE TABLE HEALTH_AI_READY_DB.TRAINING_DATASETS.MORTALITY_PREDICTION_V1 AS
SELECT
    F.PATIENT_ID,
    F.AGE,
    F.GENDER,
    F.TOTAL_DIAGNOSES,
    F.UNIQUE_ICD_CODES,
    F.HAS_MI,
    F.HAS_HEART_FAILURE,
    F.HAS_ATRIAL_FIB,
    F.TOTAL_MEDICATIONS,
    F.ON_BETA_BLOCKER,
    F.ON_ACE_INHIBITOR,
    F.ON_ANTICOAGULANT,
    F.ON_STATIN,
    F.DISTINCT_DRUG_CLASSES,
    F.TOTAL_ENCOUNTERS,
    F.INPATIENT_VISITS,
    F.AVG_LENGTH_OF_STAY,
    F.LATEST_HBA1C,
    F.LATEST_LDL,
    F.ABNORMAL_LAB_RATIO,
    CASE WHEN E.DISCHARGE_STATUS = 'EXPIRED' THEN 1 ELSE 0 END AS LABEL_MORTALITY,
    'V1'                  AS DATASET_VERSION,
    CURRENT_TIMESTAMP()   AS CREATED_AT
FROM HEALTH_AI_READY_DB.FEATURE_STORE.PATIENT_CLINICAL_FEATURES F
LEFT JOIN (
    SELECT PATIENT_ID, DISCHARGE_STATUS
    FROM HEALTH_TRANSFORM_DB.ENCOUNTERS.FACT_ENCOUNTER
    QUALIFY ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY ADMIT_DATE DESC) = 1
) E ON F.PATIENT_ID = E.PATIENT_ID;

-- Cardiac rehab adverse-event prediction training set
CREATE OR REPLACE TABLE HEALTH_AI_READY_DB.TRAINING_DATASETS.CARDIAC_ADVERSE_EVENT_V1 AS
SELECT
    C.*,
    CASE WHEN C.SAFETY_FLAG OR C.EXERCISE_TERMINATED_EARLY THEN 1 ELSE 0 END AS LABEL_ADVERSE_EVENT,
    'V1'                  AS DATASET_VERSION,
    CURRENT_TIMESTAMP()   AS CREATED_AT
FROM HEALTH_AI_READY_DB.FEATURE_STORE.CARDIAC_REHAB_FEATURES C;

------------------------------------------------------------------------
-- 13C. EMBEDDINGS – Clinical note & diagnosis code embeddings
------------------------------------------------------------------------

-- Diagnosis code embeddings stage (for storing Cortex-generated vectors)
CREATE STAGE IF NOT EXISTS HEALTH_AI_READY_DB.EMBEDDINGS.DIAGNOSIS_EMBEDDINGS_STAGE
  COMMENT = 'Stage for ICD code description embeddings';

-- Embeddings table for diagnosis descriptions
CREATE OR REPLACE TABLE HEALTH_AI_READY_DB.EMBEDDINGS.DIAGNOSIS_CODE_EMBEDDINGS (
    ICD_CODE        VARCHAR(20),
    ICD_VERSION     VARCHAR(5),
    DESCRIPTION     VARCHAR(500),
    EMBEDDING       VECTOR(FLOAT, 768),
    MODEL_USED      VARCHAR(100) DEFAULT 'snowflake-arctic-embed-m-v1.5',
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Populate diagnosis embeddings using Cortex EMBED
INSERT INTO HEALTH_AI_READY_DB.EMBEDDINGS.DIAGNOSIS_CODE_EMBEDDINGS
    (ICD_CODE, ICD_VERSION, DESCRIPTION, EMBEDDING)
SELECT DISTINCT
    ICD_CODE,
    ICD_VERSION,
    DESCRIPTION,
    SNOWFLAKE.CORTEX.EMBED_TEXT_768('snowflake-arctic-embed-m-v1.5', DESCRIPTION)
FROM HEALTH_TRANSFORM_DB.DIAGNOSES.FACT_DIAGNOSIS
WHERE DESCRIPTION IS NOT NULL;

-- Medication embeddings
CREATE OR REPLACE TABLE HEALTH_AI_READY_DB.EMBEDDINGS.MEDICATION_EMBEDDINGS (
    NDC_CODE        VARCHAR(20),
    MEDICATION_NAME VARCHAR(200),
    DRUG_CLASS      VARCHAR(50),
    EMBEDDING       VECTOR(FLOAT, 768),
    MODEL_USED      VARCHAR(100) DEFAULT 'snowflake-arctic-embed-m-v1.5',
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO HEALTH_AI_READY_DB.EMBEDDINGS.MEDICATION_EMBEDDINGS
    (NDC_CODE, MEDICATION_NAME, DRUG_CLASS, EMBEDDING)
SELECT DISTINCT
    NDC_CODE,
    MEDICATION_NAME,
    DRUG_CLASS,
    SNOWFLAKE.CORTEX.EMBED_TEXT_768('snowflake-arctic-embed-m-v1.5',
        MEDICATION_NAME || ' (' || DRUG_CLASS || ')')
FROM HEALTH_TRANSFORM_DB.MEDICATIONS.FACT_MEDICATION
WHERE MEDICATION_NAME IS NOT NULL;

-- Clinical notes embedding table (ready for NLP pipelines)
CREATE OR REPLACE TABLE HEALTH_AI_READY_DB.EMBEDDINGS.CLINICAL_NOTE_EMBEDDINGS (
    NOTE_ID         VARCHAR(50),
    PATIENT_ID      VARCHAR(50),
    ENCOUNTER_ID    VARCHAR(50),
    NOTE_TYPE       VARCHAR(50),
    NOTE_TEXT       VARCHAR(16000),
    EMBEDDING       VECTOR(FLOAT, 768),
    MODEL_USED      VARCHAR(100),
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

------------------------------------------------------------------------
-- 13D. SEMANTIC MODEL (Cortex Analyst YAML) — stored on stage
------------------------------------------------------------------------

CREATE STAGE IF NOT EXISTS HEALTH_AI_READY_DB.SEMANTIC_MODELS.SEMANTIC_STAGE
  COMMENT = 'Stage for Cortex Analyst semantic model YAML files';

------------------------------------------------------------------------
-- 13E. MODEL REGISTRY – Space for Snowflake ML Registry models
------------------------------------------------------------------------

-- Model metadata tracking table
CREATE OR REPLACE TABLE HEALTH_AI_READY_DB.MODEL_REGISTRY.MODEL_CATALOG (
    MODEL_ID            VARCHAR(100),
    MODEL_NAME          VARCHAR(200),
    MODEL_VERSION       VARCHAR(50),
    MODEL_TYPE          VARCHAR(100),
    TASK                VARCHAR(100),
    TARGET_PLATFORM     VARCHAR(50),
    TRAINING_DATASET    VARCHAR(200),
    FEATURE_COLUMNS     VARIANT,
    HYPERPARAMETERS     VARIANT,
    METRICS             VARIANT,
    DESCRIPTION         VARCHAR(2000),
    CREATED_BY          VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS              VARCHAR(20) DEFAULT 'ACTIVE'
);

-- Pre-register planned models
INSERT INTO HEALTH_AI_READY_DB.MODEL_REGISTRY.MODEL_CATALOG
  (MODEL_ID, MODEL_NAME, MODEL_VERSION, MODEL_TYPE, TASK, TARGET_PLATFORM, TRAINING_DATASET, DESCRIPTION)
VALUES
  ('MDL-001', 'ICU_MORTALITY_RETAIN', 'v1.0', 'RETAIN', 'BINARY_CLASSIFICATION', 'WAREHOUSE',
   'HEALTH_AI_READY_DB.TRAINING_DATASETS.MORTALITY_PREDICTION_V1',
   'ICU mortality prediction using RETAIN (interpretable attention model) per PyHealth pipeline'),
  ('MDL-002', 'CARDIAC_ADVERSE_TRANSFORMER', 'v1.0', 'TRANSFORMER', 'BINARY_CLASSIFICATION', 'WAREHOUSE',
   'HEALTH_AI_READY_DB.TRAINING_DATASETS.CARDIAC_ADVERSE_EVENT_V1',
   'Cardiac rehab adverse event prediction using Transformer model'),
  ('MDL-003', 'DRUG_RECOMMENDATION_SAFEDRUG', 'v1.0', 'SAFEDRUG', 'MULTI_LABEL_CLASSIFICATION', 'SNOWPARK_CONTAINER_SERVICES',
   'HEALTH_TRANSFORM_DB.MEDICATIONS.FACT_MEDICATION',
   'Safe medication recommendation with DDI constraints per PyHealth SafeDrug'),
  ('MDL-004', 'READMISSION_30DAY_GNN', 'v1.0', 'GNN', 'BINARY_CLASSIFICATION', 'WAREHOUSE',
   'HEALTH_AI_READY_DB.FEATURE_STORE.PATIENT_CLINICAL_FEATURES',
   '30-day hospital readmission prediction using Graph Neural Network');

------------------------------------------------------------------------
-- GRANT AI-layer permissions
------------------------------------------------------------------------
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTH_AI_READY_DB.FEATURE_STORE      TO ROLE HEALTH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTH_AI_READY_DB.TRAINING_DATASETS  TO ROLE HEALTH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTH_AI_READY_DB.EMBEDDINGS         TO ROLE HEALTH_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTH_AI_READY_DB.MODEL_REGISTRY     TO ROLE HEALTH_SCIENTIST;
GRANT READ   ON STAGE HEALTH_AI_READY_DB.SEMANTIC_MODELS.SEMANTIC_STAGE    TO ROLE HEALTH_SCIENTIST;
GRANT READ   ON STAGE HEALTH_AI_READY_DB.SEMANTIC_MODELS.SEMANTIC_STAGE    TO ROLE HEALTH_ANALYST;

GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTH_AI_READY_DB.FEATURE_STORE     TO ROLE HEALTH_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTH_AI_READY_DB.TRAINING_DATASETS TO ROLE HEALTH_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTH_AI_READY_DB.EMBEDDINGS        TO ROLE HEALTH_SCIENTIST;
