------------------------------------------------------------------------
-- HEALTH_DOMAIN — PHASE 11 & 12: MEDALLION ARCHITECTURE + HCLS INDUSTRY
-- RAW_DB (Bronze) → TRANSFORM_DB (Silver) → ANALYTICS_DB (Gold) → AI_READY_DB
-- Industry: Healthcare & Life Sciences (Cardiac Rehabilitation focus)
------------------------------------------------------------------------

USE ROLE HEALTH_ADMIN;

------------------------------------------------------------------------
-- ██  BRONZE LAYER (HEALTH_RAW_DB) — Raw ingested tables
------------------------------------------------------------------------

-- Patients (EHR source)
CREATE OR REPLACE TABLE HEALTH_RAW_DB.EHR_INGEST.RAW_PATIENTS (
    RAW_ID              NUMBER AUTOINCREMENT,
    PATIENT_ID          VARCHAR(50),
    FIRST_NAME          VARCHAR(100),
    LAST_NAME           VARCHAR(100),
    DATE_OF_BIRTH       DATE,
    GENDER              VARCHAR(10),
    ETHNICITY           VARCHAR(50),
    SSN                 VARCHAR(11),
    ADDRESS             VARCHAR(500),
    PHONE               VARCHAR(20),
    EMAIL               VARCHAR(200),
    INSURANCE_ID        VARCHAR(50),
    PRIMARY_LANGUAGE    VARCHAR(50),
    MARITAL_STATUS      VARCHAR(20),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM       VARCHAR(50) DEFAULT 'EHR_IMPORT',
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Encounters / Visits
CREATE OR REPLACE TABLE HEALTH_RAW_DB.EHR_INGEST.RAW_ENCOUNTERS (
    RAW_ID              NUMBER AUTOINCREMENT,
    ENCOUNTER_ID        VARCHAR(50),
    PATIENT_ID          VARCHAR(50),
    ENCOUNTER_TYPE      VARCHAR(30),
    ADMIT_DATE          TIMESTAMP_NTZ,
    DISCHARGE_DATE      TIMESTAMP_NTZ,
    DEPARTMENT          VARCHAR(100),
    ATTENDING_PROVIDER  VARCHAR(100),
    FACILITY_CODE       VARCHAR(20),
    ADMIT_DIAGNOSIS_CODE VARCHAR(20),
    DISCHARGE_STATUS    VARCHAR(30),
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Diagnoses
CREATE OR REPLACE TABLE HEALTH_RAW_DB.EHR_INGEST.RAW_DIAGNOSES (
    RAW_ID              NUMBER AUTOINCREMENT,
    DIAGNOSIS_ID        VARCHAR(50),
    ENCOUNTER_ID        VARCHAR(50),
    PATIENT_ID          VARCHAR(50),
    ICD_CODE            VARCHAR(20),
    ICD_VERSION         VARCHAR(5),
    DESCRIPTION         VARCHAR(500),
    DIAGNOSIS_TYPE      VARCHAR(30),
    DIAGNOSIS_DATE      DATE,
    CLINICIAN           VARCHAR(100),
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Medications
CREATE OR REPLACE TABLE HEALTH_RAW_DB.EHR_INGEST.RAW_MEDICATIONS (
    RAW_ID              NUMBER AUTOINCREMENT,
    MEDICATION_ID       VARCHAR(50),
    ENCOUNTER_ID        VARCHAR(50),
    PATIENT_ID          VARCHAR(50),
    NDC_CODE            VARCHAR(20),
    MEDICATION_NAME     VARCHAR(200),
    DOSAGE              VARCHAR(100),
    ROUTE               VARCHAR(50),
    FREQUENCY           VARCHAR(50),
    PRESCRIBER          VARCHAR(100),
    START_DATE          DATE,
    END_DATE            DATE,
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Procedures
CREATE OR REPLACE TABLE HEALTH_RAW_DB.EHR_INGEST.RAW_PROCEDURES (
    RAW_ID              NUMBER AUTOINCREMENT,
    PROCEDURE_ID        VARCHAR(50),
    ENCOUNTER_ID        VARCHAR(50),
    PATIENT_ID          VARCHAR(50),
    CPT_CODE            VARCHAR(20),
    ICD_PROC_CODE       VARCHAR(20),
    DESCRIPTION         VARCHAR(500),
    PROCEDURE_DATE      DATE,
    PERFORMING_PROVIDER VARCHAR(100),
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Lab Results & Vitals
CREATE OR REPLACE TABLE HEALTH_RAW_DB.LAB_INGEST.RAW_LAB_RESULTS (
    RAW_ID              NUMBER AUTOINCREMENT,
    LAB_ID              VARCHAR(50),
    ENCOUNTER_ID        VARCHAR(50),
    PATIENT_ID          VARCHAR(50),
    LOINC_CODE          VARCHAR(20),
    TEST_NAME           VARCHAR(200),
    RESULT_VALUE        VARCHAR(100),
    RESULT_NUMERIC      FLOAT,
    UNIT                VARCHAR(50),
    REFERENCE_LOW       FLOAT,
    REFERENCE_HIGH      FLOAT,
    ABNORMAL_FLAG       VARCHAR(10),
    COLLECTED_AT        TIMESTAMP_NTZ,
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE HEALTH_RAW_DB.LAB_INGEST.RAW_VITAL_SIGNS (
    RAW_ID              NUMBER AUTOINCREMENT,
    VITAL_ID            VARCHAR(50),
    ENCOUNTER_ID        VARCHAR(50),
    PATIENT_ID          VARCHAR(50),
    VITAL_TYPE          VARCHAR(50),
    VALUE_NUMERIC       FLOAT,
    UNIT                VARCHAR(20),
    MEASURED_AT         TIMESTAMP_NTZ,
    MEASURED_BY         VARCHAR(100),
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Cardiac Rehabilitation Sessions (from cardiac rehab skill)
CREATE OR REPLACE TABLE HEALTH_RAW_DB.CARDIAC_REHAB_INGEST.RAW_REHAB_REFERRALS (
    RAW_ID              NUMBER AUTOINCREMENT,
    REFERRAL_ID         VARCHAR(50),
    PATIENT_ID          VARCHAR(50),
    REFERRING_PHYSICIAN VARCHAR(100),
    QUALIFYING_DIAGNOSIS VARCHAR(100),
    CARDIAC_EVENT_DATE  DATE,
    LVEF_PERCENT        FLOAT,
    GXT_PEAK_HR         INT,
    GXT_PEAK_METS       FLOAT,
    ISCHEMIC_THRESHOLD  VARCHAR(100),
    AACVPR_RISK_CATEGORY VARCHAR(20),
    REFERRAL_DATE       DATE,
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE HEALTH_RAW_DB.CARDIAC_REHAB_INGEST.RAW_REHAB_SESSIONS (
    RAW_ID              NUMBER AUTOINCREMENT,
    SESSION_ID          VARCHAR(50),
    REFERRAL_ID         VARCHAR(50),
    PATIENT_ID          VARCHAR(50),
    SESSION_NUMBER      INT,
    SESSION_DATE        DATE,
    MODALITY            VARCHAR(100),
    DURATION_MINUTES    INT,
    TARGET_HR_LOW       INT,
    TARGET_HR_HIGH      INT,
    RESTING_HR          INT,
    PEAK_HR             INT,
    RECOVERY_HR         INT,
    RESTING_BP_SYSTOLIC INT,
    RESTING_BP_DIASTOLIC INT,
    PEAK_BP_SYSTOLIC    INT,
    PEAK_BP_DIASTOLIC   INT,
    POST_BP_SYSTOLIC    INT,
    POST_BP_DIASTOLIC   INT,
    RPE_PEAK            INT,
    SPO2_MIN            FLOAT,
    ECG_RHYTHM          VARCHAR(100),
    ECG_MONITOR_MINUTES INT,
    SYMPTOMS            VARCHAR(500),
    ADVERSE_EVENTS      VARCHAR(500),
    EXERCISE_TERMINATED_EARLY BOOLEAN DEFAULT FALSE,
    TERMINATION_REASON  VARCHAR(200),
    NOTES               VARCHAR(2000),
    THERAPIST           VARCHAR(100),
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE HEALTH_RAW_DB.CARDIAC_REHAB_INGEST.RAW_REHAB_OUTCOMES (
    RAW_ID              NUMBER AUTOINCREMENT,
    OUTCOME_ID          VARCHAR(50),
    REFERRAL_ID         VARCHAR(50),
    PATIENT_ID          VARCHAR(50),
    MEASUREMENT_TYPE    VARCHAR(50),
    MEASUREMENT_POINT   VARCHAR(30),
    MEASUREMENT_DATE    DATE,
    SIX_MIN_WALK_METERS FLOAT,
    PEAK_METS           FLOAT,
    DASI_SCORE          FLOAT,
    PHQ9_SCORE          INT,
    WEIGHT_KG           FLOAT,
    BMI                 FLOAT,
    WAIST_CM            FLOAT,
    HBA1C               FLOAT,
    LDL                 FLOAT,
    HDL                 FLOAT,
    TOTAL_CHOLESTEROL   FLOAT,
    TRIGLYCERIDES       FLOAT,
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Claims
CREATE OR REPLACE TABLE HEALTH_RAW_DB.CLAIMS_INGEST.RAW_CLAIMS (
    RAW_ID              NUMBER AUTOINCREMENT,
    CLAIM_ID            VARCHAR(50),
    PATIENT_ID          VARCHAR(50),
    ENCOUNTER_ID        VARCHAR(50),
    PAYER_ID            VARCHAR(50),
    PAYER_NAME          VARCHAR(200),
    CLAIM_TYPE          VARCHAR(30),
    SERVICE_DATE        DATE,
    CPT_CODE            VARCHAR(20),
    DRG_CODE            VARCHAR(10),
    BILLED_AMOUNT       NUMBER(12,2),
    ALLOWED_AMOUNT      NUMBER(12,2),
    PAID_AMOUNT         NUMBER(12,2),
    PATIENT_RESPONSIBILITY NUMBER(12,2),
    CLAIM_STATUS        VARCHAR(30),
    DENIAL_REASON       VARCHAR(200),
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

------------------------------------------------------------------------
-- ██  SILVER LAYER (HEALTH_TRANSFORM_DB) — Cleaned & conformed
------------------------------------------------------------------------

-- Conformed patients
CREATE OR REPLACE TABLE HEALTH_TRANSFORM_DB.PATIENTS.DIM_PATIENT AS
SELECT
    PATIENT_ID,
    UPPER(TRIM(FIRST_NAME))     AS FIRST_NAME,
    UPPER(TRIM(LAST_NAME))      AS LAST_NAME,
    DATE_OF_BIRTH,
    DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) AS AGE,
    UPPER(TRIM(GENDER))         AS GENDER,
    TRIM(ETHNICITY)             AS ETHNICITY,
    SSN,
    ADDRESS,
    PHONE,
    LOWER(TRIM(EMAIL))          AS EMAIL,
    INSURANCE_ID,
    PRIMARY_LANGUAGE,
    MARITAL_STATUS,
    CURRENT_TIMESTAMP()         AS TRANSFORMED_AT
FROM HEALTH_RAW_DB.EHR_INGEST.RAW_PATIENTS
QUALIFY ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY _LOADED_AT DESC) = 1;

ALTER TABLE HEALTH_TRANSFORM_DB.PATIENTS.DIM_PATIENT
  SET TAG HEALTH_GOVERNANCE_DB.TAGS.SENSITIVITY = 'PHI',
      TAG HEALTH_GOVERNANCE_DB.TAGS.DATA_DOMAIN = 'PATIENT';

ALTER TABLE HEALTH_TRANSFORM_DB.PATIENTS.DIM_PATIENT
  MODIFY COLUMN SSN
    SET MASKING POLICY HEALTH_GOVERNANCE_DB.POLICIES.MASK_SSN;

ALTER TABLE HEALTH_TRANSFORM_DB.PATIENTS.DIM_PATIENT
  MODIFY COLUMN DATE_OF_BIRTH
    SET MASKING POLICY HEALTH_GOVERNANCE_DB.POLICIES.MASK_DOB;

ALTER TABLE HEALTH_TRANSFORM_DB.PATIENTS.DIM_PATIENT
  MODIFY COLUMN FIRST_NAME
    SET MASKING POLICY HEALTH_GOVERNANCE_DB.POLICIES.MASK_PATIENT_NAME;

ALTER TABLE HEALTH_TRANSFORM_DB.PATIENTS.DIM_PATIENT
  MODIFY COLUMN LAST_NAME
    SET MASKING POLICY HEALTH_GOVERNANCE_DB.POLICIES.MASK_PATIENT_NAME;

-- Care team assignments (for row access policy)
CREATE OR REPLACE TABLE HEALTH_TRANSFORM_DB.PATIENTS.CARE_TEAM_ASSIGNMENTS (
    ASSIGNMENT_ID       NUMBER AUTOINCREMENT,
    PATIENT_ID          VARCHAR(50),
    CARE_TEAM_ID        VARCHAR(50),
    CLINICIAN_USER      VARCHAR(100),
    ROLE_IN_TEAM        VARCHAR(50),
    ASSIGNED_DATE       DATE,
    END_DATE            DATE
);

-- Conformed encounters
CREATE OR REPLACE TABLE HEALTH_TRANSFORM_DB.ENCOUNTERS.FACT_ENCOUNTER AS
SELECT
    ENCOUNTER_ID,
    PATIENT_ID,
    UPPER(TRIM(ENCOUNTER_TYPE))   AS ENCOUNTER_TYPE,
    ADMIT_DATE,
    DISCHARGE_DATE,
    DATEDIFF('DAY', ADMIT_DATE, COALESCE(DISCHARGE_DATE, CURRENT_TIMESTAMP())) AS LENGTH_OF_STAY_DAYS,
    DEPARTMENT,
    ATTENDING_PROVIDER,
    FACILITY_CODE,
    ADMIT_DIAGNOSIS_CODE,
    DISCHARGE_STATUS,
    CURRENT_TIMESTAMP()           AS TRANSFORMED_AT
FROM HEALTH_RAW_DB.EHR_INGEST.RAW_ENCOUNTERS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ENCOUNTER_ID ORDER BY _LOADED_AT DESC) = 1;

-- Conformed diagnoses with ICD mapping
CREATE OR REPLACE TABLE HEALTH_TRANSFORM_DB.DIAGNOSES.FACT_DIAGNOSIS AS
SELECT
    DIAGNOSIS_ID,
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIM(ICD_CODE)       AS ICD_CODE,
    ICD_VERSION,
    DESCRIPTION,
    DIAGNOSIS_TYPE,
    DIAGNOSIS_DATE,
    CASE
      WHEN ICD_CODE ILIKE 'I21%' OR ICD_CODE ILIKE '410%' THEN 'ACUTE_MI'
      WHEN ICD_CODE ILIKE 'I25%' OR ICD_CODE ILIKE '414%' THEN 'CHRONIC_IHD'
      WHEN ICD_CODE ILIKE 'I50%' OR ICD_CODE ILIKE '428%' THEN 'HEART_FAILURE'
      WHEN ICD_CODE ILIKE 'I20%' OR ICD_CODE ILIKE '413%' THEN 'ANGINA'
      WHEN ICD_CODE ILIKE 'Z95%'                          THEN 'CARDIAC_DEVICE'
      WHEN ICD_CODE ILIKE 'I48%'                          THEN 'ATRIAL_FIBRILLATION'
      WHEN ICD_CODE ILIKE 'I42%'                          THEN 'CARDIOMYOPATHY'
      ELSE 'OTHER'
    END AS CARDIAC_CATEGORY,
    CURRENT_TIMESTAMP()   AS TRANSFORMED_AT
FROM HEALTH_RAW_DB.EHR_INGEST.RAW_DIAGNOSES
QUALIFY ROW_NUMBER() OVER (PARTITION BY DIAGNOSIS_ID ORDER BY _LOADED_AT DESC) = 1;

-- Conformed medications
CREATE OR REPLACE TABLE HEALTH_TRANSFORM_DB.MEDICATIONS.FACT_MEDICATION AS
SELECT
    MEDICATION_ID,
    ENCOUNTER_ID,
    PATIENT_ID,
    NDC_CODE,
    MEDICATION_NAME,
    DOSAGE,
    ROUTE,
    FREQUENCY,
    PRESCRIBER,
    START_DATE,
    END_DATE,
    CASE
      WHEN MEDICATION_NAME ILIKE '%metoprolol%' OR MEDICATION_NAME ILIKE '%atenolol%'
           OR MEDICATION_NAME ILIKE '%carvedilol%' THEN 'BETA_BLOCKER'
      WHEN MEDICATION_NAME ILIKE '%lisinopril%' OR MEDICATION_NAME ILIKE '%enalapril%'
           OR MEDICATION_NAME ILIKE '%ramipril%'   THEN 'ACE_INHIBITOR'
      WHEN MEDICATION_NAME ILIKE '%warfarin%' OR MEDICATION_NAME ILIKE '%heparin%'
           OR MEDICATION_NAME ILIKE '%apixaban%'   THEN 'ANTICOAGULANT'
      WHEN MEDICATION_NAME ILIKE '%amiodarone%' OR MEDICATION_NAME ILIKE '%sotalol%'
                                                   THEN 'ANTIARRHYTHMIC'
      WHEN MEDICATION_NAME ILIKE '%atorvastatin%' OR MEDICATION_NAME ILIKE '%rosuvastatin%'
                                                   THEN 'STATIN'
      WHEN MEDICATION_NAME ILIKE '%aspirin%' OR MEDICATION_NAME ILIKE '%clopidogrel%'
                                                   THEN 'ANTIPLATELET'
      ELSE 'OTHER'
    END AS DRUG_CLASS,
    CURRENT_TIMESTAMP()   AS TRANSFORMED_AT
FROM HEALTH_RAW_DB.EHR_INGEST.RAW_MEDICATIONS
QUALIFY ROW_NUMBER() OVER (PARTITION BY MEDICATION_ID ORDER BY _LOADED_AT DESC) = 1;

-- Conformed lab results
CREATE OR REPLACE TABLE HEALTH_TRANSFORM_DB.LAB_VITALS.FACT_LAB_RESULT AS
SELECT
    LAB_ID,
    ENCOUNTER_ID,
    PATIENT_ID,
    LOINC_CODE,
    TEST_NAME,
    RESULT_VALUE,
    RESULT_NUMERIC,
    UNIT,
    REFERENCE_LOW,
    REFERENCE_HIGH,
    ABNORMAL_FLAG,
    CASE
      WHEN RESULT_NUMERIC IS NOT NULL
           AND REFERENCE_LOW IS NOT NULL
           AND REFERENCE_HIGH IS NOT NULL THEN
        CASE
          WHEN RESULT_NUMERIC < REFERENCE_LOW  THEN 'LOW'
          WHEN RESULT_NUMERIC > REFERENCE_HIGH THEN 'HIGH'
          ELSE 'NORMAL'
        END
      ELSE ABNORMAL_FLAG
    END AS COMPUTED_FLAG,
    COLLECTED_AT,
    CURRENT_TIMESTAMP() AS TRANSFORMED_AT
FROM HEALTH_RAW_DB.LAB_INGEST.RAW_LAB_RESULTS
QUALIFY ROW_NUMBER() OVER (PARTITION BY LAB_ID ORDER BY _LOADED_AT DESC) = 1;

-- Conformed cardiac rehab referrals
CREATE OR REPLACE TABLE HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_REFERRAL AS
SELECT
    REFERRAL_ID,
    PATIENT_ID,
    REFERRING_PHYSICIAN,
    QUALIFYING_DIAGNOSIS,
    CARDIAC_EVENT_DATE,
    LVEF_PERCENT,
    GXT_PEAK_HR,
    GXT_PEAK_METS,
    ISCHEMIC_THRESHOLD,
    UPPER(TRIM(AACVPR_RISK_CATEGORY)) AS AACVPR_RISK_CATEGORY,
    CASE
      WHEN LVEF_PERCENT >= 50 AND GXT_PEAK_METS >= 7 THEN 'LOW'
      WHEN LVEF_PERCENT BETWEEN 40 AND 49             THEN 'MODERATE'
      WHEN LVEF_PERCENT < 40                            THEN 'HIGH'
      ELSE UPPER(TRIM(AACVPR_RISK_CATEGORY))
    END AS COMPUTED_RISK,
    REFERRAL_DATE,
    DATEDIFF('DAY', CARDIAC_EVENT_DATE, REFERRAL_DATE) AS DAYS_EVENT_TO_REFERRAL,
    CURRENT_TIMESTAMP() AS TRANSFORMED_AT
FROM HEALTH_RAW_DB.CARDIAC_REHAB_INGEST.RAW_REHAB_REFERRALS
QUALIFY ROW_NUMBER() OVER (PARTITION BY REFERRAL_ID ORDER BY _LOADED_AT DESC) = 1;

-- Conformed cardiac rehab sessions with hemodynamic calculations
CREATE OR REPLACE TABLE HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_SESSION AS
SELECT
    SESSION_ID,
    REFERRAL_ID,
    PATIENT_ID,
    SESSION_NUMBER,
    SESSION_DATE,
    MODALITY,
    DURATION_MINUTES,
    TARGET_HR_LOW,
    TARGET_HR_HIGH,
    RESTING_HR,
    PEAK_HR,
    RECOVERY_HR,
    RESTING_BP_SYSTOLIC,
    RESTING_BP_DIASTOLIC,
    PEAK_BP_SYSTOLIC,
    PEAK_BP_DIASTOLIC,
    POST_BP_SYSTOLIC,
    POST_BP_DIASTOLIC,
    RPE_PEAK,
    SPO2_MIN,
    ECG_RHYTHM,
    ECG_MONITOR_MINUTES,
    SYMPTOMS,
    ADVERSE_EVENTS,
    EXERCISE_TERMINATED_EARLY,
    TERMINATION_REASON,
    THERAPIST,
    -- Karvonen intensity calculation
    CASE WHEN TARGET_HR_HIGH > 0 AND RESTING_HR > 0
      THEN ROUND((PEAK_HR - RESTING_HR)::FLOAT / NULLIF(TARGET_HR_HIGH - RESTING_HR, 0) * 100, 1)
      ELSE NULL
    END AS ACHIEVED_HRR_PERCENT,
    -- Recovery assessment
    CASE WHEN PEAK_HR > 0 AND RECOVERY_HR > 0
      THEN PEAK_HR - RECOVERY_HR
      ELSE NULL
    END AS HR_RECOVERY_DELTA,
    -- Safety flags
    CASE
      WHEN PEAK_BP_SYSTOLIC > 250 OR PEAK_BP_DIASTOLIC > 115 THEN TRUE
      WHEN PEAK_BP_SYSTOLIC < RESTING_BP_SYSTOLIC - 10       THEN TRUE
      WHEN SPO2_MIN < 88                                       THEN TRUE
      WHEN EXERCISE_TERMINATED_EARLY                           THEN TRUE
      ELSE FALSE
    END AS SAFETY_FLAG,
    CURRENT_TIMESTAMP() AS TRANSFORMED_AT
FROM HEALTH_RAW_DB.CARDIAC_REHAB_INGEST.RAW_REHAB_SESSIONS
QUALIFY ROW_NUMBER() OVER (PARTITION BY SESSION_ID ORDER BY _LOADED_AT DESC) = 1;

-- Conformed rehab outcomes
CREATE OR REPLACE TABLE HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_OUTCOME AS
SELECT
    OUTCOME_ID,
    REFERRAL_ID,
    PATIENT_ID,
    MEASUREMENT_TYPE,
    MEASUREMENT_POINT,
    MEASUREMENT_DATE,
    SIX_MIN_WALK_METERS,
    PEAK_METS,
    DASI_SCORE,
    PHQ9_SCORE,
    WEIGHT_KG,
    BMI,
    WAIST_CM,
    HBA1C,
    LDL,
    HDL,
    TOTAL_CHOLESTEROL,
    TRIGLYCERIDES,
    CASE
      WHEN PHQ9_SCORE >= 20 THEN 'SEVERE'
      WHEN PHQ9_SCORE >= 15 THEN 'MODERATELY_SEVERE'
      WHEN PHQ9_SCORE >= 10 THEN 'MODERATE'
      WHEN PHQ9_SCORE >= 5  THEN 'MILD'
      ELSE 'MINIMAL'
    END AS DEPRESSION_SEVERITY,
    CURRENT_TIMESTAMP() AS TRANSFORMED_AT
FROM HEALTH_RAW_DB.CARDIAC_REHAB_INGEST.RAW_REHAB_OUTCOMES
QUALIFY ROW_NUMBER() OVER (PARTITION BY OUTCOME_ID ORDER BY _LOADED_AT DESC) = 1;

------------------------------------------------------------------------
-- ██  GOLD LAYER (HEALTH_ANALYTICS_DB) — Consumption-ready aggregations
------------------------------------------------------------------------

-- Cardiac rehab program summary per patient
CREATE OR REPLACE VIEW HEALTH_ANALYTICS_DB.CARDIAC_OUTCOMES.V_REHAB_PROGRAM_SUMMARY AS
SELECT
    R.PATIENT_ID,
    R.REFERRAL_ID,
    R.QUALIFYING_DIAGNOSIS,
    R.COMPUTED_RISK                                   AS RISK_CATEGORY,
    R.LVEF_PERCENT,
    R.REFERRAL_DATE,
    R.DAYS_EVENT_TO_REFERRAL,
    COUNT(S.SESSION_ID)                               AS TOTAL_SESSIONS,
    MIN(S.SESSION_DATE)                               AS FIRST_SESSION_DATE,
    MAX(S.SESSION_DATE)                               AS LAST_SESSION_DATE,
    DATEDIFF('WEEK', MIN(S.SESSION_DATE), MAX(S.SESSION_DATE)) AS PROGRAM_WEEKS,
    AVG(S.DURATION_MINUTES)                           AS AVG_DURATION_MIN,
    AVG(S.ACHIEVED_HRR_PERCENT)                       AS AVG_HRR_PERCENT,
    AVG(S.RPE_PEAK)                                   AS AVG_RPE,
    SUM(CASE WHEN S.SAFETY_FLAG THEN 1 ELSE 0 END)   AS SAFETY_FLAG_COUNT,
    SUM(CASE WHEN S.EXERCISE_TERMINATED_EARLY THEN 1 ELSE 0 END) AS EARLY_TERMINATIONS,
    ROUND(COUNT(S.SESSION_ID)::FLOAT / 36 * 100, 1)  AS ADHERENCE_RATE_PCT
FROM HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_REFERRAL R
LEFT JOIN HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_SESSION S
  ON R.REFERRAL_ID = S.REFERRAL_ID
GROUP BY 1,2,3,4,5,6,7;

-- Cardiac outcome comparison (baseline vs discharge)
CREATE OR REPLACE VIEW HEALTH_ANALYTICS_DB.CARDIAC_OUTCOMES.V_OUTCOME_COMPARISON AS
SELECT
    B.PATIENT_ID,
    B.REFERRAL_ID,
    B.SIX_MIN_WALK_METERS   AS BASELINE_6MWT,
    D.SIX_MIN_WALK_METERS   AS DISCHARGE_6MWT,
    D.SIX_MIN_WALK_METERS - B.SIX_MIN_WALK_METERS AS DELTA_6MWT,
    CASE WHEN (D.SIX_MIN_WALK_METERS - B.SIX_MIN_WALK_METERS) >= 25 THEN 'CLINICALLY_SIGNIFICANT' ELSE 'NOT_SIGNIFICANT' END AS MCID_6MWT,
    B.PEAK_METS             AS BASELINE_METS,
    D.PEAK_METS             AS DISCHARGE_METS,
    D.PEAK_METS - B.PEAK_METS AS DELTA_METS,
    B.PHQ9_SCORE            AS BASELINE_PHQ9,
    D.PHQ9_SCORE            AS DISCHARGE_PHQ9,
    D.PHQ9_SCORE - B.PHQ9_SCORE AS DELTA_PHQ9,
    B.BMI                   AS BASELINE_BMI,
    D.BMI                   AS DISCHARGE_BMI,
    B.LDL                   AS BASELINE_LDL,
    D.LDL                   AS DISCHARGE_LDL,
    B.HBA1C                 AS BASELINE_HBA1C,
    D.HBA1C                 AS DISCHARGE_HBA1C
FROM HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_OUTCOME B
JOIN HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_OUTCOME D
  ON B.REFERRAL_ID = D.REFERRAL_ID
WHERE B.MEASUREMENT_POINT = 'BASELINE'
  AND D.MEASUREMENT_POINT = 'DISCHARGE';

-- Population health – cardiac cohort overview
CREATE OR REPLACE VIEW HEALTH_ANALYTICS_DB.POPULATION_HEALTH.V_CARDIAC_COHORT AS
SELECT
    P.GENDER,
    P.ETHNICITY,
    CASE
      WHEN P.AGE < 45 THEN '<45'
      WHEN P.AGE < 55 THEN '45-54'
      WHEN P.AGE < 65 THEN '55-64'
      WHEN P.AGE < 75 THEN '65-74'
      ELSE '75+'
    END AS AGE_GROUP,
    R.COMPUTED_RISK AS RISK_CATEGORY,
    R.QUALIFYING_DIAGNOSIS,
    COUNT(DISTINCT P.PATIENT_ID) AS PATIENT_COUNT,
    AVG(R.LVEF_PERCENT)          AS AVG_LVEF,
    AVG(R.GXT_PEAK_METS)        AS AVG_PEAK_METS
FROM HEALTH_TRANSFORM_DB.PATIENTS.DIM_PATIENT P
JOIN HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_REFERRAL R
  ON P.PATIENT_ID = R.PATIENT_ID
GROUP BY 1,2,3,4,5;

-- Clinical dashboard – daily session metrics
CREATE OR REPLACE VIEW HEALTH_ANALYTICS_DB.CLINICAL_DASHBOARDS.V_DAILY_SESSION_METRICS AS
SELECT
    S.SESSION_DATE,
    COUNT(*)                                          AS SESSIONS_CONDUCTED,
    COUNT(DISTINCT S.PATIENT_ID)                      AS UNIQUE_PATIENTS,
    AVG(S.DURATION_MINUTES)                           AS AVG_DURATION,
    AVG(S.PEAK_HR)                                    AS AVG_PEAK_HR,
    AVG(S.RPE_PEAK)                                   AS AVG_RPE,
    SUM(CASE WHEN S.SAFETY_FLAG THEN 1 ELSE 0 END)   AS SAFETY_INCIDENTS,
    SUM(S.ECG_MONITOR_MINUTES)                        AS TOTAL_ECG_MINUTES
FROM HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_SESSION S
GROUP BY 1
ORDER BY 1 DESC;

-- Quality measures – CMS cardiac rehab metrics
CREATE OR REPLACE VIEW HEALTH_ANALYTICS_DB.QUALITY_MEASURES.V_CMS_CARDIAC_REHAB AS
SELECT
    DATE_TRUNC('MONTH', R.REFERRAL_DATE)::DATE AS REFERRAL_MONTH,
    COUNT(DISTINCT R.REFERRAL_ID)              AS TOTAL_REFERRALS,
    COUNT(DISTINCT S.REFERRAL_ID)              AS REFERRALS_WITH_SESSIONS,
    ROUND(COUNT(DISTINCT S.REFERRAL_ID)::FLOAT / NULLIF(COUNT(DISTINCT R.REFERRAL_ID), 0) * 100, 1) AS ENROLLMENT_RATE_PCT,
    AVG(R.DAYS_EVENT_TO_REFERRAL)              AS AVG_DAYS_TO_REFERRAL,
    COUNT(DISTINCT CASE WHEN PS.TOTAL_SESSIONS >= 36 THEN R.REFERRAL_ID END) AS COMPLETED_PROGRAMS,
    ROUND(COUNT(DISTINCT CASE WHEN PS.TOTAL_SESSIONS >= 36 THEN R.REFERRAL_ID END)::FLOAT
          / NULLIF(COUNT(DISTINCT S.REFERRAL_ID), 0) * 100, 1) AS COMPLETION_RATE_PCT
FROM HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_REFERRAL R
LEFT JOIN HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_SESSION S
  ON R.REFERRAL_ID = S.REFERRAL_ID
LEFT JOIN (
    SELECT REFERRAL_ID, COUNT(*) AS TOTAL_SESSIONS
    FROM HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_SESSION
    GROUP BY 1
) PS ON R.REFERRAL_ID = PS.REFERRAL_ID
GROUP BY 1
ORDER BY 1 DESC;

-- Financial – claims analysis
CREATE OR REPLACE VIEW HEALTH_ANALYTICS_DB.FINANCIAL.V_CLAIMS_SUMMARY AS
SELECT
    DATE_TRUNC('MONTH', C.SERVICE_DATE)::DATE AS SERVICE_MONTH,
    C.PAYER_NAME,
    C.CLAIM_TYPE,
    COUNT(*)                                  AS CLAIM_COUNT,
    SUM(C.BILLED_AMOUNT)                      AS TOTAL_BILLED,
    SUM(C.ALLOWED_AMOUNT)                     AS TOTAL_ALLOWED,
    SUM(C.PAID_AMOUNT)                        AS TOTAL_PAID,
    SUM(C.BILLED_AMOUNT - C.PAID_AMOUNT)      AS TOTAL_WRITE_OFF,
    ROUND(SUM(C.PAID_AMOUNT) / NULLIF(SUM(C.BILLED_AMOUNT), 0) * 100, 1) AS COLLECTION_RATE_PCT,
    SUM(CASE WHEN C.CLAIM_STATUS = 'DENIED' THEN 1 ELSE 0 END) AS DENIALS
FROM HEALTH_RAW_DB.CLAIMS_INGEST.RAW_CLAIMS C
GROUP BY 1,2,3
ORDER BY 1 DESC;

-- Session-level hemodynamic trend (for therapists)
CREATE OR REPLACE VIEW HEALTH_ANALYTICS_DB.CLINICAL_DASHBOARDS.V_PATIENT_HEMODYNAMIC_TREND AS
SELECT
    S.PATIENT_ID,
    S.SESSION_NUMBER,
    S.SESSION_DATE,
    S.MODALITY,
    S.RESTING_HR,
    S.PEAK_HR,
    S.RECOVERY_HR,
    S.HR_RECOVERY_DELTA,
    S.RESTING_BP_SYSTOLIC || '/' || S.RESTING_BP_DIASTOLIC AS RESTING_BP,
    S.PEAK_BP_SYSTOLIC || '/' || S.PEAK_BP_DIASTOLIC       AS PEAK_BP,
    S.RPE_PEAK,
    S.ACHIEVED_HRR_PERCENT,
    S.SPO2_MIN,
    S.ECG_RHYTHM,
    S.SAFETY_FLAG,
    S.DURATION_MINUTES
FROM HEALTH_TRANSFORM_DB.CARDIAC_REHAB.FACT_REHAB_SESSION S
ORDER BY S.PATIENT_ID, S.SESSION_NUMBER;
